### ISSUE TITLE
更新了potplayer后无法使用

### ISSUE THREAD

**Issue by trumna789** [jqtmviyu/UserScripts#1]
potplayer 自动更新后好像就无法使用了

**Comment by jqtmviyu** [comment]
抱歉, 因为我一直在macos下使用iina, 没有报这个错. 
原作者已经修复. https://github.com/bpking1/embyExternalUrl/commit/070a88496f6072020fc3f56c9aea1f5de8e368e5

我照抄把 DeviceId参数 添加上去, 已经可以了.
