### ISSUE TITLE
点击按钮启动pot后存在报错，提示该文件不存在或被锁定

### ISSUE THREAD

**Issue by FYYXS** [jqtmviyu/UserScripts#2]
点击按钮启动pot后存在报错，提示该文件不存在或被锁定，最新版Chrome

**Comment by jqtmviyu** [comment]
你可以尝试下原作者的脚本 https://github.com/bpking1/embyExternalUrl , 看是否会有同样的问题.

cent  118
emby 4.9.0.30
pot  1.7.21024

正常.

**Comment by FYYXS** [comment]
> 你可以尝试下原作者的脚本https://github.com/bpking1/embyExternalUrl，看看是否还会有相同的问题。
> 
> cent 118 emby 4.9.0.30 pot 1.7.21024
> 
> 正常。

感谢您的答复，windows端的chrome最新版本似乎出现了问题，将chrome降级可以解决。经过查看，点击按钮启动pot后存在报错，提示该文件不存在或被锁定。查看pot的详细信息后发现：请求路径是http//，而不是http:// 手动复制链接进pot就能正常播放了
